"""Add module_number to lessons

Revision ID: 52c30f467009
Revises: f901d18886f4
Create Date: 2025-08-15 19:17:09.817779

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '52c30f467009'
down_revision = 'f901d18886f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column('lesson', sa.Column('module_number', sa.Integer(), nullable=True))
    
    # Update existing lessons with module numbers based on order
    # Module 1: lessons 1-2, Module 2: lessons 3-4, etc.
    op.execute("""
        UPDATE lesson SET module_number = CASE
            WHEN "order" <= 2 THEN 1
            WHEN "order" <= 4 THEN 2
            WHEN "order" <= 6 THEN 3
            WHEN "order" <= 8 THEN 4
            WHEN "order" <= 10 THEN 5
            ELSE 6
        END
        WHERE module_number IS NULL
    """)
    
    # Now make it NOT NULL
    op.alter_column('lesson', 'module_number', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'module_number')
    # ### end Alembic commands ### 