"""Create lesson_completion table

Revision ID: 9a4144907561
Revises: 52c30f467009
Create Date: 2025-08-18 20:22:29.098010

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9a4144907561'
down_revision = '52c30f467009'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 