services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: resilient_mastery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/resilient_mastery
      - SECRET_KEY=dev-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    command: sh -c "python -m alembic upgrade head && python seed_data.py && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  pgdata: 